### ISSUE TITLE
Issue with Plesk

### ISSUE THREAD

**Issue by ScriptVortexDE** [rorry47/mailcow_module_WHMCS#4]
How can i fixe this ? 
https://auroa.link/view/7ea69f5b-9e2a-4896-9f66-04320b42179e.jpg

**Comment by ScriptVortexDE** [comment]
I have self fixt it, you must change the filename from /lib/MailcowAPI.php to only MailcowAPI.php

**Comment by rorry47** [comment]
Hello! Thanks! Fixed :)
